export const products = [
  {
    id: 1,
    logo: "logo-red-dragon.jpg",
    title: "IPS LCD Gaming Monitor",
    img: "monitor.png",
    off: 5,
    price: 450,
    oldPrice: 560,
    rate: 91,
    cant: 1,
  },
  {
    id: 2,
    logo: "logo-jbl.jpg",
    title: "Baffle BOSE",
    img: "parlante-jbl.png",
    off: 5,
    price: 650,
    oldPrice: 740,
    rate: 95,
    cant: 1,
  },
  {
    id: 3,
    logo: "logo-apple.jpg",
    title: "iPhone 14 Series",
    img: "iphone.png",
    off: 10,
    price: 1500,
    oldPrice: 1800,
    rate: 98,
    cant: 1,
  },
  {
    id: 4,
    logo: "logo-control.png",
    title: "HAVIT HV-G92 Gamepad",
    img: "control.png",
    off: 40,
    price: 120,
    oldPrice: 160,
    rate: 88,
    cant: 1,
  },
  {
    id: 5,
    logo: "logo-red-dragon.jpg",
    title: "IPS LCD Gaming Monitor",
    img: "monitor.png",
    off: 5,
    price: 450,
    oldPrice: 560,
    rate: 91,
    cant: 1,
  },
];

export const categories = [
  { img: "phone_iphone", title: "Phones" },
  { img: "desktop_windows", title: "Computers" },
  { img: "watch_wake", title: "Smartwatch" },
  { img: "photo_camera", title: "Camera" },
  { img: "headphones", title: "Headphones" },
  { img: "videogame_asset", title: "Gaming" },
];
